=== Ahoo-Wang/Wow/wow-schema/src/main/resources/META-INF/wow-schema/AggregatedDomainEventStream.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "minLength": 1,
      "description": "The ID of the domain event stream."
    },
    "contextName": {
      "type": "string",
      "minLength": 1,
      "description": "The name of the context to which the domain event stream belongs"
    },
    "aggregateName": {
      "type": "string",
      "minLength": 1,
      "description": "The name of the aggregate to which the domain event stream belongs"
    },
    "header": {
      "type": "object",
      "properties": {
        "user_agent": {
          "type": "string",
          "description": "user agent"
        },
        "remote_ip": {
          "type": "string",
          "description": "remote ip"
        },
        "trace_id": {
          "type": "string",
          "description": "trace id"
        },
        "command_operator": {
          "type": "string",
          "description": "command operator"
        },
        "local_first": {
          "type": "boolean",
          "description": "local first"
        },
        "command_wait_endpoint": {
          "type": "string",
          "format": "url",
          "description": "command wait endpoint"
        },
        "command_wait_stage": {
          "type": "string",
          "enum": [
            "SENT",
            "PROCESSED",
            "SNAPSHOT",
            "PROJECTED",
            "EVENT_HANDLED",
            "SAGA_HANDLED"
          ],
          "default": "PROCESSED"
        }
      },
      "description": "message header",
      "additionalProperties": true
    },
    "tenantId": {
      "type": "string",
      "minLength": 1,
      "description": "The tenant id of the aggregate"
    },
    "aggregateId": {
      "type": "string",
      "minLength": 1,
      "description": "The id of the aggregate"
    },
    "ownerId": {
      "type": "string",
      "description": "The owner ID of the aggregate resource",
      "default": ""
    },
    "spaceId": {
      "type": "string",
      "description": "The space ID of the aggregate resource",
      "default": ""
    },
    "commandId": {
      "type": "string",
      "minLength": 1,
      "description": "The ID of the command message."
    },
    "requestId": {
      "type": "string",
      "minLength": 1,
      "description": "The request ID of the command message, which is used to check the idempotency of the command message"
    },
    "version": {
      "type": "integer",
      "format": "int32",
      "description": "The version of the domain event stream"
    },
    "body": {
      "type": "array",
      "items": {
        "anyOf": []
      },
      "minItems": 1,
      "description": "A list of domain events for the domain event stream"
    },
    "createTime": {
      "type": "integer",
      "format": "int64",
      "description": "The time when the domain event stream was created"
    }
  },
  "required": [
    "id",
    "contextName",
    "aggregateName",
    "header",
    "tenantId",
    "aggregateId",
    "ownerId",
    "spaceId",
    "commandId",
    "requestId",
    "version",
    "body",
    "createTime"
  ]
}

=== Ahoo-Wang/Wow/migration/migrate-data/src/test/resources/ninex-example/cart-stream-v2.json
{"id":"0VY3GwZk4OmV006","contextName":"example-service","aggregateName":"cart","header":{"command_operator":"customer-1","trace_id":"0VY3GwZi4OmV005","upstream_id":"0VY3GwZi4OmV005","upstream_name":"add_cart_item"},"aggregateId":"0VY3GwKq4OmV001","tenantId":"(0)","ownerId":"customer-1","spaceId":"","commandId":"0VY3GwZi4OmV005","requestId":"0VY3GwZi4OmV005","version":2,"body":[{"id":"0VY3GwZk4OmV007","name":"cart_item_added","revision":"0.0.1","bodyType":"me.ahoo.wow.example.api.cart.CartItemAdded","body":{"added":{"productId":"product-2","quantity":3}}}],"createTime":1792004186816}
